**Step 1 — Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import os

**Step 2 — Load Dataset**

In [2]:
df = pd.read_csv("../data/raw/ev_sales.csv")

**Step 3 — Inspect the Dataset** 
Purpose: Understand the structure of the data before changing anything.

In [3]:
df.head()

   Year    Month        State Vehicle_Category  EV_Sales
0  2021  January  Maharashtra      Electric 2W      4200
1  2021  January  Maharashtra      Electric 3W      1800
2  2021  January  Maharashtra      Electric 4W       850
3  2021  January        Delhi      Electric 2W      2300
4  2021  January        Delhi      Electric 3W      2100

In [4]:
df.tail()

     Year     Month          State Vehicle_Category  EV_Sales
283  2022  December      Karnataka      Electric 3W      5680
284  2022  December      Karnataka      Electric 4W      2860
285  2022  December  Uttar Pradesh      Electric 2W     11100
286  2022  December  Uttar Pradesh      Electric 3W      9320
287  2022  December  Uttar Pradesh      Electric 4W      2700

In [5]:
df.shape

(288, 5)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              288 non-null    int64
 1   Month             288 non-null    object
 2   State             288 non-null    object
 3   Vehicle_Category  288 non-null    object
 4   EV_Sales          288 non-null    int64
dtypes: int64(2), object(3)
memory usage: 11.4+ KB

In [7]:
df.columns

Index(['Year', 'Month', 'State', 'Vehicle_Category', 'EV_Sales'], dtype='object')

In [8]:
df.describe()

             Year      EV_Sales
count   288.00000    288.000000
mean   2021.50000   3911.527778
std       0.50087   2747.793494
min    2021.00000    500.000000
25%    2021.00000   1735.000000
50%    2021.50000   3250.000000
75%    2022.00000   5312.500000
max    2022.00000  15000.000000

**Step 4 — Check Missing Values**

In [9]:
df.isnull().sum()

Year                0
Month               0
State               0
Vehicle_Category    0
EV_Sales            0
dtype: int64

**Step 5 — Check Duplicate Rows**

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df = df.drop_duplicates()

**Step 6 — Check Data Types**

In [12]:
df.dtypes

Year                 int64
Month               object
State               object
Vehicle_Category    object
EV_Sales             int64
dtype: object

**Step 7 — Convert Month Name to Month Number**

In [13]:
month_map = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}

df["Month"] = df["Month"].map(month_map)

In [14]:
df.head()

   Year  Month        State Vehicle_Category  EV_Sales
0  2021      1  Maharashtra      Electric 2W      4200
1  2021      1  Maharashtra      Electric 3W      1800
2  2021      1  Maharashtra      Electric 4W       850
3  2021      1        Delhi      Electric 2W      2300
4  2021      1        Delhi      Electric 3W      2100


**Step 8 — Create Date Column**

In [15]:
df["Date"] = pd.to_datetime(
    dict(
        year=df["Year"],
        month=df["Month"],
        day=1
    )
)

**Step 9 — Rearrange Columns**

In [16]:
df = df[
    [
        "Date",
        "Year",
        "Month",
        "State",
        "Vehicle_Category",
        "EV_Sales"
    ]
]

**Step 10 — Sort the Data**

In [17]:
df = df.sort_values(
    ["Date", "State", "Vehicle_Category"]
)

In [18]:
df

          Date  Year  Month          State Vehicle_Category  EV_Sales
3   2021-01-01  2021      1          Delhi      Electric 2W      2300
4   2021-01-01  2021      1          Delhi      Electric 3W      2100
5   2021-01-01  2021      1          Delhi      Electric 4W       700
6   2021-01-01  2021      1      Karnataka      Electric 2W      3100
7   2021-01-01  2021      1      Karnataka      Electric 3W      1200
..         ...   ...    ...            ...              ...       ...
277 2022-12-01  2022     12    Maharashtra      Electric 3W      6800
278 2022-12-01  2022     12    Maharashtra      Electric 4W      3250
285 2022-12-01  2022     12  Uttar Pradesh      Electric 2W     11100
286 2022-12-01  2022     12  Uttar Pradesh      Electric 3W      9320
287 2022-12-01  2022     12  Uttar Pradesh      Electric 4W      2700

[288 rows x 6 columns]

**Step 11 — Reset the Index**

In [19]:
df.reset_index(drop=True, inplace=True)

**Step 12 — Save the Cleaned Dataset**
Create the output folder if needed:

In [20]:
os.makedirs("../data/processed", exist_ok=True)

In [21]:
df.to_csv(
    "../data/processed/ev_sales_cleaned.csv",
    index=False
)

**Step 13 — Final Verification**
Reload the saved file:

In [22]:
clean_df = pd.read_csv(
    "../data/processed/ev_sales_cleaned.csv",
    parse_dates=["Date"]
)

clean_df.head()

        Date  Year  Month      State Vehicle_Category  EV_Sales
0 2021-01-01  2021      1      Delhi      Electric 2W      2300
1 2021-01-01  2021      1      Delhi      Electric 3W      2100
2 2021-01-01  2021      1      Delhi      Electric 4W       700
3 2021-01-01  2021      1  Karnataka      Electric 2W      3100
4 2021-01-01  2021      1  Karnataka      Electric 3W      1200